"""
Report Generator for LILA Evaluation
Reads `comprehensive_metrics.json` and produces a polished Markdown report (`EVALUATION_REPORT.md`).
Features:
- Statistical Summary (Mean, Median, Stdev)
- ASCII Histograms for Latency and Token Usage
- Task-by-Task Comparison Table
- Tool Usage Analysis
"""

import json
import statistics
import math
from pathlib import Path
from typing import List, Dict, Any

INPUT_FILE = Path(__file__).parent / "comprehensive_metrics.json"
OUTPUT_FILE = Path(__file__).parent / "../documentation/EVALUATION_REPORT.md"

def load_data() -> Dict[str, Any]:
    if not INPUT_FILE.exists():
        print(f"Error: {INPUT_FILE} not found. Run eval_comprehensive.py first.")
        return {}
    with open(INPUT_FILE, "r") as f:
        return json.load(f)

def generate_ascii_histogram(data: List[float], bins: int = 10, width: int = 40, label_unit: str = "") -> str:
    """Generates a simple ASCII histogram for a dataset."""
    if not data:
        return "No data available."
    
    min_val = min(data)
    max_val = max(data)
    
    if min_val == max_val:
        return f"  All values are {min_val:.2f}{label_unit}"
        
    bin_size = (max_val - min_val) / bins
    histogram = [0] * bins
    
    for val in data:
        idx = int((val - min_val) / bin_size)
        if idx >= bins: idx = bins - 1
        histogram[idx] += 1
        
    max_count = max(histogram) if histogram else 1
    
    lines = []
    lines.append("```")
    for i in range(bins):
        range_start = min_val + (i * bin_size)
        range_end = range_start + bin_size
        count = histogram[i]
        bar_len = int((count / max_count) * width)
        bar = "█" * bar_len
        lines.append(f"{range_start:6.1f} - {range_end:6.1f}{label_unit} | {bar} ({count})")
    lines.append("```")
    return "\n".join(lines)

def generate_markdown(data: Dict[str, Any]) -> str:
    details = data.get("details", [])
    if not details:
        return "# Evaluation Report\n\nNo data found."

    # Extract series
    latencies = [r["latency_seconds"] for r in details]
    steps = [r["steps"] for r in details]
    tool_calls = [r["tool_calls"] for r in details]
    
    successes = [r for r in details if r["success"]]
    failures = [r for r in details if not r["success"]]
    
    # Calculate Statistics
    total_runs = len(details)
    success_rate = len(successes) / total_runs * 100
    
    avg_latency = statistics.mean(latencies)
    stdev_latency = statistics.stdev(latencies) if len(latencies) > 1 else 0
    
    # Report Construction
    md = []
    md.append("# 📊 LILA System Evaluation Report")
    md.append(f"**Date Generated:** {Path(__file__).stat().st_mtime}") # Placeholder for file time
    md.append("\n## 1. Executive Summary")
    md.append(f"- **Total Runs:** {total_runs}")
    md.append(f"- **Success Rate:** {success_rate:.1f}%")
    md.append(f"- **Avg Latency:** {avg_latency:.2f}s (σ={stdev_latency:.2f}s)")
    
    md.append("\n## 2. Efficiency Analysis")
    
    md.append("### Latency Distribution (Seconds)")
    md.append(generate_ascii_histogram(latencies, label_unit="s"))

    md.append("\n## 3. Robustness & Graph Behavior")
    md.append("| Metric | Mean | Median | Max |")
    md.append("| :--- | :---: | :---: | :---: |")
    md.append(f"| **Steps** | {statistics.mean(steps):.1f} | {statistics.median(steps):.1f} | {max(steps)} |")
    md.append(f"| **Tool Calls** | {statistics.mean(tool_calls):.1f} | {statistics.median(tool_calls):.1f} | {max(tool_calls)} |")
    
    # Correlation Check (Simple heuristic)
    md.append("\n### Observations")
    if failures:
        fail_steps = statistics.mean([r["steps"] for r in failures])
        pass_steps = statistics.mean([r["steps"] for r in successes]) if successes else 0
        md.append(f"- **Failure Complexity:** Failed runs took on average {fail_steps:.1f} steps, while successful runs took {pass_steps:.1f} steps.")
        if fail_steps > pass_steps * 1.5:
            md.append("  - *Insight:* Failures tend to involve longer, potentially looped execution paths.")
        elif fail_steps < pass_steps:
            md.append("  - *Insight:* Failures tend to abort early (crashes or quick rejections).")
    else:
        md.append("- No failures detected in this dataset.")

    md.append("\n## 4. Task Breakdown")
    md.append("| Task Name | Success | Latency (s) | Steps | Tool Calls |")
    md.append("| :--- | :---: | :---: | :---: | :---: |")
    
    # Sort by task name
    details.sort(key=lambda x: x["task_name"])
    
    for r in details:
        status_icon = "✅" if r["success"] else "❌"
        md.append(f"| {r['task_name']} | {status_icon} | {r['latency_seconds']:.2f} | {r['steps']} | {r['tool_calls']} |")
        
    md.append("\n---")
    md.append("*Generated by LILA Report Tool*")
    
    return "\n".join(md)

def main():
    print(f"Reading data from: {INPUT_FILE}")
    data = load_data()
    if not data:
        return
        
    print("Generating report...")
    report_content = generate_markdown(data)
    
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(report_content)
        
    print(f"✅ Report saved to: {OUTPUT_FILE}")
    print("\nPreview Top 10 Lines:")
    print("-" * 30)
    print("\n".join(report_content.splitlines()[:10]))
    print("-" * 30)

if __name__ == "__main__":
    main()
